import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Service from 'App/Models/Service'

export default class ServiceSeeder extends BaseSeeder {
  public async run () {
    await Service.createMany([
      { scope: 'DB', service: 'Setup Database', hour_needed: 1},
      { scope: 'DB', service: 'Deploy Database', hour_needed: 1},
      { scope: 'DB', service: 'Create modeling', hour_needed: 1},
      { scope: 'DB', service: 'Verify/Update modeling', hour_needed: 1},
      { scope: 'DB', service: 'Setup Docker', hour_needed: 1},
      { scope: 'DB', service: 'Verify/Update Docker', hour_needed: 1},
      { scope: 'DB', service: 'Create/Verify Migration', hour_needed: 1},
      { scope: 'DB', service: 'Create Seeder', hour_needed: 1},
      { scope: 'DB', service: 'Verify/Update Seeder', hour_needed: 1},
      { scope: 'DB', service: 'Create Factory', hour_needed: 1},
      { scope: 'DB', service: 'Verify/Update Factory', hour_needed: 1},
      { scope: 'DB', service: 'Create Model', hour_needed: 1},
      { scope: 'DB', service: 'Verify/Update Model', hour_needed: 1},

      { scope: 'Backend', service: 'Setup Backend', hour_needed: 1},
      { scope: 'Backend', service: 'Deploy Backend', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function CREATE (controller)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function LIST (controller)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function UPDATE (controller)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function SHOW (controller)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function FILTER (controller)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function DELETE (controller)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function CREATE (repository)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function LIST (repository)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function UPDATE (repository)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function SHOW (repository)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function FILTER (repository)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify function DELETE (repository)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify CREATE (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify LIST (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify UPDATE (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify SHOW (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify FILTER (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify DELETE (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify CREATE (ACL)', hour_needed: 1},
      { scope: 'Backend', service: 'Create/Verify UPDATE (ACL)', hour_needed: 1},

      { scope: 'Frontend', service: 'Setup Frontend', hour_needed: 1},
      { scope: 'Frontend', service: 'Deploy Frontend', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify Template', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page CREATE (structure)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page CREATE (style)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page CREATE (functions)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page CREATE (formaters)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page CREATE (Validators)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page CREATE (ACL)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page UPDATE (structure)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page UPDATE (style)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page UPDATE (functions)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page UPDATE (formaters)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page UPDATE (Validators)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page UPDATE (ACL)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page SHOW (structure)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page SHOW (style)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page SHOW (functions)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page SHOW (formaters)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page SHOW (ACL)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page LIST (structure)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page LIST (style)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page LIST (functions)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page LIST (formaters)', hour_needed: 1},
      { scope: 'Frontend', service: 'Create/Verify page LIST (ACL)', hour_needed: 1},

      { scope: 'Mobile', service: 'Setup Mobile', hour_needed: 1},
      { scope: 'Mobile', service: 'Deploy Mobile', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify Template', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page CREATE (structure)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page CREATE (style)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page CREATE (functions)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page CREATE (formaters)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page CREATE (Validators)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page CREATE (ACL)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page UPDATE (structure)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page UPDATE (style)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page UPDATE (functions)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page UPDATE (formaters)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page UPDATE (Validators)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page UPDATE (ACL)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page SHOW (structure)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page SHOW (style)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page SHOW (functions)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page SHOW (formaters)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page SHOW (ACL)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page LIST (structure)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page LIST (style)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page LIST (functions)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page LIST (formaters)', hour_needed: 1},
      { scope: 'Mobile', service: 'Create/Verify page LIST (ACL)', hour_needed: 1},
    ])
  }
}
